name: Trigger Vercel Cron Job

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes UTC
  workflow_dispatch:        # allows manual trigger

jobs:
  call-vercel-api:
    runs-on: ubuntu-latest
    steps:
      - name: Curl to Vercel endpoint
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://securefintech.vercel.app/api/run-batch-model
